ATLAS-3222:- Update httpclient jar version to 4.5.3 to fix NoSuchMethodError error
Change-Id: If47909376585d72bf766dab667e0ca99cdc324c0
Signed-off-by: Sarath Subramanian <sarath@apache.org>
(cherry picked from commit 25c3bf9abc4ac893e67318855387be7c15a33fcc)